### PR TITLE
Expose number of valid (non-nan) values

### PR DESCRIPTION
**Pull request by tvk568**
A bit cryptic, but this was already computed as `Ns`. It validates with no difference between python and opencl versions. Not tested against R, lmk if you want me to.

### CODE REVIEW

**Comment by mortvest** [comment]
Looks okay, but the opencl backend should return the number of valids even if the detailed_results is false.

**Comment by tvk568** [comment]
Sure. Will fix.

**Comment by tvk568** [comment]
Had some trouble recompiling futhark until I realised that the build was killed due to my system running OOM :P...
I have regenerated `bfastfinal.py` using latest futhark master. Still validates.

Also I have included an unrelated commit (sorry), there was a check on `self.detailed` that caused an error when `find_magnitudes` was set to false. Corrected to `self.detailed_results`.

**Comment by mortvest** [comment]
Solid work, but you also need to add valids to python-mp

**Comment by tvk568** [comment]
I have amended the first and second commit to include the python-mp backend. It validates.

**Comment by mortvest** [comment]
Good work!

**Pull request merged**
